public class ConstValueClass {

	public static final int MIN_BABY = 1, MIN_CHILD = 3, MIN_TEEN = 13, MIN_ADULT = 19,
							MAX_CHILD = 12, MAX_TEEN = 18, MAX_ADULT = 64;
	public static final int BABY = 1, CHILD = 2, TEEN = 3, ADULT = 4, OLD = 5;
	public static final float DISABLE_DISCOUNT_RATE = 0.6f, MERIT_DISCOUNT_RATE = 0.5f,
								MULTICHILD_DISCOUNT_RATE = 0.8f, PREGNANT_DISCOUNT_RATE = 0.85f;
	public static final int MAX_COUNT = 10, MIN_COUNT = 1;
	public static final int ALLDAY_TICKET_PRICE_REALBABY = 0, ALLDAY_TICKET_PRICE_BABY = 15000,
							ALLDAY_TICKET_PRICE_ADULT = 59000, ALLDAY_TICKET_PRICE_YOUTH = 52000,
							ALLDAY_TICKET_PRICE_CHILD_AND_OLDMAN = 46000;
	public static final int NIGHT_TICKET_PRICE_REALBABY = 0, NIGHT_TICKET_PRICE_BABY = 15000,
							NIGHT_TICKET_PRICE_ADULT = 47000, NIGHT_TICKET_PRICE_YOUTH = 41000,
							NIGHT_TICKET_PRICE_CHILD_AND_OLDMAN = 35000;
	public static final int ALLDAY_TICKET_PRICE_DISABLED_ADULT = 29500,
							ALLDAY_TICKET_PRICE_DISABLED_YOUTH = 26000, 
							ALLDAY_TICKET_PRICE_DISABLED_CHILD = 23000;
	public static final int NIGHT_TICKET_PRICE_DISABLED_ADULT = 23500, NIGHT_TICKET_PRICE_DISABLED_YOUTH = 20500,
							NIGHT_TICKET_PRICE_DISABLED_CHILD = 17500;
	public static final int  ALLDAY_TICKET_PRICE_MUTI_CHILD_ADULT = 43400, ALLDAY_TICKET_PRICE_MUTI_CHILD_YOUTH = 37800, 
							ALLDAY_TICKET_PRICE_MUTI_CHILD_CHILD = 32900;
	public static final int  NIGHT_TICKET_PRICE_MUTI_CHILD_ADULT = 35000, NIGHT_TICKET_PRICE_MUTI_CHILD_YOUTH = 30100,
							NIGHT_TICKET_PRICE_MUTI_CHILD_CHILD = 25200;
	public static final int  ALLDAY_TICKET_PRICE_PREGNANT_WOMAN = 31000, NIGHT_TICKET_PRICE_PREGNANT_WOMAN = 25000;
	
	
}
